### ISSUE TITLE
Device compatibility issue

### ISSUE THREAD

**Issue by kaist-jisungpark** [SoundMetrics/aris-integration-sdk#124]
Dear,

I have simple questions.
- Is this SDK okay for use on Linux?
- Is this SDK compatible with the d i d s o n sonar?

Thanks and Regards

**Comment by curtnichols** [comment]
Good morning,

> Is this SDK okay for use on Linux?

Controlling and receiving images from an ARIS requires the use of **Google Protocol Buffers** (protobuf), and **TCP** & **UDP** sockets. While the SDK doesn't provide example code for Linux, one can write such code on Linux.

> Is this SDK compatible with the d i d s o n sonar?

No, ARIS has different protocols than DIDSON. If you have further DIDSON questions, please write to support@soundmetrics.com.

Hope this helps.

**Comment by curtnichols** [comment]
I'm closing this issue as inactive. Feel free to re-open it or open another issue if necessary.
