### ISSUE TITLE
connect.c:send_date_time() appears to send only the date

### ISSUE THREAD

**Issue by curtnichols** [SoundMetrics/aris-integration-sdk#45]
As currently formatted, `send_date_time()` sends only the date, and in the wrong format. This code:

    /* Format date as %Y-%m-%d */
    strftime(now_str, sizeof(now_str), "%F", &now);

should probably be:

    constexpr auto fmt = "%Y-%b-%d %H:%M:%S"; // 2017-Apr-01 12:34:56
    strftime(now_str, sizeof(now_str), fmt, &now);

We should probably then test to make sure the sample program works.

**Comment by fvasquez** [comment]
That's weird.  This bug was fixed by PR #38.  The line of code in question looks like this now in the public repo.

`strftime(now_str, sizeof(now_str), "%Y-%b-%d %T", &now);`

Are you looking at an out-of-date submodule?

**Comment by curtnichols** [comment]
Ah, you're right. I'm working in a private repo w/submodule. Closing.
