### ISSUE TITLE
Mention FrameRate code

### ISSUE THREAD

**Issue by fvasquez** [SoundMetrics/aris-integration-sdk#59]
A common/code/FrameRate sudirectory was recently added to this repo.

## Expected Behavior

C++ code provided in common/code/FrameRate subdirectory should be mentioned in README and ARIS Integration SDK document.

## Current Behavior

There is no mention of C++ code provided in common/code/FrameRate subdirectory in either the README or ARIS Integration SDK document.

## Context

cycle period * pings per frame calculation is insufficient.  Customers should be aware of `CalculateMaxFrameRate` function that we provide.

**Comment by curtnichols** [comment]
Resovled in ab497e8b70e8f959be12848afd5a6bf9b23f3644.
